apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        resources:
          #limits:
          #  memory: "128Mi"
          # cpu: "500m"
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
